React-state初步学习
x5plan/git-blog pull request #18
Opened 2024-01-25 15:49 UTC by monazite1s

2024-01-25 17:57 UTC, AntaresQAQ approved these changes

2024-01-25 18:04 UTC, AntaresQAQ requested changes

2024-01-25 18:04 UTC, AntaresQAQ commented on Monazite/2024/01/25/React-state.md
> +1. **组件进行第一次渲染。**此时传入 `useState` 的初始值作为 `state` 变量的值。
<img width="640" alt="image" src="https://github.com/x5plan/git-blog/assets/37372723/e36b5e24-e93c-41b1-916f-2cb4370bb957">

这个 `**` 似乎有语法错误

2024-01-25 18:04 UTC, AntaresQAQ commented on Monazite/2024/01/25/React-state.md
> +1. **组件进行第一次渲染。**此时传入 `useState` 的初始值作为 `state` 变量的值。
You should insert a space between `**` and `此时`.

and the next line ditto

2024-01-26 02:56 UTC, monazite1s commented on Monazite/2024/01/25/React-state.md
> +1. **组件进行第一次渲染。**此时传入 `useState` 的初始值作为 `state` 变量的值。
Thanks for error correction and I'll pay attention next time.

2024-01-26 04:28 UTC, AntaresQAQ approved these changes

2024-02-27 04:34 UTC, houforever approved these changes

2024-02-27 04:36 UTC, closed without merging